#!/bin/bash -ex

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

echo Setting up Python virtual environment
BUILDDIR="$(pwd)/build"
mkdir -p "${BUILDDIR}"
python3 -m venv "${BUILDDIR}/venv"
. "${BUILDDIR}/venv/bin/activate"

echo Updating pip
pip3 install -U pip

echo Adding pyinstaller
# Temporary workaround until
# https://github.com/pyinstaller/pyinstaller/pull/6218 is in a
# PyInstaller release
export STRIP=/usr/bin/strip
pip3 install pyinstaller

echo Installing update_manifest_released requirements
pip3 install -r ${SCRIPTPATH}/requirements.txt

# Customize _buildversion.py if build info available in environment
if [ ! -z "${VERSION}" -a ! -z "${BLD_NUM}" ]; then
    VERSIONPATH="${BUILDDIR}/version"
    mkdir -p "${VERSIONPATH}"
    cat <<EOF > "${VERSIONPATH}/_buildversion.py"
__version__ = "${VERSION}"
__build__ = "${BLD_NUM}"
EOF
else
    VERSIONPATH=""
fi

echo Compiling update_manifest_released
PYINSTDIR=$(pwd)/build/pyinstaller
mkdir -p ${PYINSTDIR}

pyinstaller --log-level DEBUG \
    --workpath ${PYINSTDIR} \
    --specpath ${PYINSTDIR} \
    --distpath dist --noconfirm \
    --onefile \
    --paths ${SCRIPTPATH}/update_manifest_released/scripts \
    ${SCRIPTPATH}/update_manifest_released/scripts/update_manifest_released.py
